src/Entity/Quack.php
<?php

namespace App\Entity;

use App\Repository\QuackRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuackRepository::class)]
class Quack
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'integer', nullable: false)]
    private ?int $duckID = null;
    #[ORM\Column(type: 'string', nullable: false)]
    private ?string $duckProfilePicture = null;

    public function getDuckProfilePicture(): ?string
    {
        return $this->duckProfilePicture;
    }

    public function setDuckProfilePicture(?string $duckProfilePicture): void
    {
        $this->duckProfilePicture = $duckProfilePicture;
    }

    public function getDuckID(): ?int
    {
        return $this->duckID;
    }

    public function setDuckID(?int $duckID): void
    {
        $this->duckID = $duckID;
    }

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: 'string')]
    private ?string $author = null;
    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $imgSrc = null;
    #[ORM\Column(length: 500)]
    private ?string $tags = null;
    #[ORM\OneToMany(mappedBy: 'parentId', targetEntity: self::class)]
    private Collection $comments;
    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'comments')]
    private  ?self $parentId =null;

    #[ORM\Column]
    private ?bool $Display = null;

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(?string $author): void
    {
        $this->author = $author;
    }

    public function getImgSrc(): ?string
    {
        return $this->imgSrc;
    }

    public function setImgSrc(?string $imgSrc): void
    {
        $this->imgSrc = $imgSrc;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): void
    {
        $this->tags = $tags;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->comments = new ArrayCollection();
        $this->Display = true;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getParentsId(): ?self
    {
        return $this->parentId;
    }

    public function setParentId(?self $parentId): static
    {
        $this->parentId = $parentId;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComments(self $comments): static
    {
        if (!$this->comments->contains($comments)) {
            $this->comments->add($comments);
            $comments->setParentId($this);
        }

        return $this;
    }

    public function removeComments(self $comments): static
    {
        if ($this->parentId->removeElement($comments)) {
            // set the owning side to null (unless already changed)
            if ($comments->getParentsId() === $this) {
                $comments->setParentId(null);
            }
        }

        return $this;
    }

    public function isDisplay(): ?bool
    {
        return $this->Display;
    }

    public function setDisplay(bool $Display): static
    {
        $this->Display = $Display;

        return $this;
    }
}

src/Form/QuackType.php
<?php

namespace App\Form;

use App\Entity\Quack;
use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Quack::class,
        ]);
    }
}

src/Form/Type/QuackType.php
<?php

namespace App\Form\Type;

use App\Entity\Quack;
use Doctrine\DBAL\Types\StringType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content', TextareaType::class)
            ->add('tags')
            ->add('imgSrc')
            ->add('save', SubmitType::class);
    }
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class'=>Quack::class,
        ]);
    }
}

src/Controller/QuackController.php
<?php

namespace App\Controller;

use App\Entity\Quack;
use App\Entity\Ducks;
use App\Form\Type\QuackType;
use App\Form\Type\SearchType;
use App\Model\SearchData;
use App\Repository\QuackRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\DocBlock\Tags\Author;
use Symfony\Component\HttpFoundation\Request;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuackController extends AbstractController
{
    #[Route('/quack', name: 'app_quack')]
    public function index(): Response
    {
        return $this->render('quack/index.html.twig', [
            'controller_name' => 'QuackController',
        ]);
    }

    #[Route('/', name: 'allquacks')]
    public function listAllQuacks(QuackRepository $quackRepository, Request $request): Response
    {
        $searchData =new SearchData();
        $form = $this->createForm(SearchType::class, $searchData);
        $form ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $searchData->page = $request->query->getInt('page', 1);
            $quacks = $quackRepository->findBySearch($searchData);
//            dd($quacks);

            return $this->render('quack/listAllQuacks.html.twig', [
                'form'=>$form,
                'quacks'=>$quacks
            ]);
        }

        $allQuacks = $quackRepository->findAll();
        return $this->render('quack/listAllQuacks.html.twig', [
            'form'=> $form,
            'quacks' => $allQuacks
        ]);
    }

    #[Route('/quack/addquack', name: 'add_quackForm')]
    public function addQuackForm(Request $request, EntityManagerInterface $entityManager): Response
    {
        $quack = new Quack();
//        $Quack->setContent($content);
//        $Quack->setCreatedAt(new \DateTime());
//        $form = $this->createFormBuilder($quack)
//            ->add('Content', TextareaType::class)
//            ->add('CreatedAt', DateType::class)
//            ->add('save', SubmitType::class, ['label'=>'Create Quack'])
//            ->getForm();
//        $entityManager->persist($quack);
//        $entityManager->flush();
//        return new Response('Saved new product with id' . $quack->getId());
        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED');
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $author = $user->getDuckname();
            $duckId = $user->getId();
            $profilePicture = $user->getProfilePicture();
            $quack->setDuckProfilePicture($profilePicture);
            $quack->setDuckID($duckId);
            $quack->setAuthor($author);
            $quack = $form->getData();
            $entityManager->persist($quack);
            $entityManager->flush();
            return $this->redirectToRoute('allquacks');
        }
        return $this->render('quack/addQuack.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/quack/modifyquack/{id}', name: 'modify_quack')]
    public function modifyQuack(Quack $quack, EntityManagerInterface $entityManager, Request $request): Response
    {
        $form = $this->createForm(QuackType::class, $quack);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $quack = $form->getData();
            $entityManager->persist($quack);
            $entityManager->flush();
            return $this->redirectToRoute('allquacks');
        }

        return $this->render('quack/modifyQuack.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/quack/deletequack/{id}', name: 'delete_quack')]
    public function deleteQuack(Quack $quack, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($quack);
        $entityManager->flush();
        return $this->redirectToRoute('allquacks');
    }

    #[Route('/quack/display/{id}', name : 'app_quack_display')]
    public function dontDisplayQuack (Quack $quack, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $quack->setDisplay(false);
        $entityManager->persist($quack);
        $entityManager->flush();
        return $this->redirectToRoute('allquacks');
    }

}

templates/quack/add.html.twig
{%  extends 'base.html.twig' %}
{% block title %}Modifier un Quack{% endblock %}
{%  block body %}

    <body class="bg-halloween-theme">
    <div class="container mx-auto p-4">
        <h1 class="text-2xl font-bold mb-4 text-halloween-orange">Quacker !</h1>
        <div class="bg-halloween-black p-6 rounded shadow-md">
            {{ form_start(form) }}
            <div class="mb-4">
                {{ form_widget(form.content, {'attr': {'class': 'w-full p-2 border rounded text-halloween-orange bg-halloween-black'}}) }}
            </div>
            <div class="mb-4">
                <button class="btn btn-primary text-white p-2 rounded bg-primary">Postez votre Quack!</button>
            </div>
            {{ form_end(form) }}
            <a href="{{ path('quack_list') }}" class="btn btn-halloween-secondary">Retour à la liste</a>
        </div>
    </div>
    </body>
{%  endblock %}

templates/quack/addQuack.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('style.css') }}">

{% endblock %}
{% block body %}
    <div class="flex justify-center">


        {{ form_start(form, {'attr':{'class':'w-full flex flex-col items-center'}}) }}
        {{ form_errors(form) }}
        <h2 class="card-title flex justify-center">Nouveau Quack !</h2>
        {{ form_widget(form.content, {'attr':{'class': ' w-3/5 textarea textarea-error'}}) }}
        <div>
            {{ form_label(form.imgSrc) }}
            {{ form_widget(form.imgSrc, {'attr':{'class': 'w-96 textarea textarea-error'}}) }}

        </div>
        <div>
            {{ form_label(form.tags) }}
            {{ form_widget(form.tags, {'attr':{'class': 'w-96 textarea textarea-error'}}) }}
        </div>
        {{ form_row(form.save, {'attr':{'class':' btn btn-primary bg-primary text-white'  }}) }}
        {{ form_end(form) }}


    </div>
    {#    <div class="flex justify-center"> #}
    {#        <div class="w-3/5 bg-primary flex justify-center"> #}
    {#            <div> #}
    {#                {{ form(form) }} #}
    {#            </div> #}

    {#        </div> #}
    {#    </div> #}

    {% endblock %}

templates/quack/edit.html.twig
{%  extends 'base.html.twig' %}
{% block title %}Modifier un Quack{% endblock %}
{%  block body %}

    <body class="bg-halloween-theme">
    <div class="container mx-auto p-4">
        <h1 class="text-2xl font-bold mb-4 text-halloween-orange">Édition du Quack</h1>
        <div class="bg-halloween-black p-6 rounded shadow-md">
{{ form_start(form) }}
            <div class="mb-4">
                {{ form_widget(form.content, {'attr': {'class': 'w-full p-2 border rounded text-halloween-orange bg-halloween-black'}}) }}
            </div>
            <div class="mb-4">
                <button class="btn btn-primary text-white p-2 rounded bg-primary">Enregistrer les modifications</button>
            </div>
{{ form_end(form) }}
            <a href="{{ path('quack_list') }}" class="btn btn-halloween-secondary">Retour à la liste</a>
        </div>
    </div>
</body>
{%  endblock %}

templates/quack/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello QuackController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/user/Documents/QuackNet/QuackNet/src/Controller/QuackController.php'|file_link(0) }}">src/Controller/QuackController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/user/Documents/QuackNet/QuackNet/templates/quack/index.html.twig'|file_link(0) }}">templates/quack/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/quack/listAllQuacks.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="flex justify-center ">
{#        <h2 class=" flex justify-center">List de tous les Quack</h2>#}
        <div>
            {% include 'search/index.html.twig' with {
                form:form
            } only %}
        </div>
    </div>
    <ul class="flex items-center flex-col gap-3.5">
        {% for quack in quacks %}
            {% if quack.parentsId==''  and quack.display == true %}
                <div class=" card w-3/5 bg-base-100 shadow-xl ">
                    <div class="card-body">
                        {#                <h2 class="card-title">{{ quack.id }}</h2> #}
                        <div class="flex flex-row items-center">
                            <img src="{{ quack.duckProfilePicture }}" alt="{{ quack.duckProfilePicture }}" class="w-48">
                            <p><a href="{{ path('app_profile', {'id': quack.duckID}) }}">{{ quack.author }}</a></p>
                        </div>

                        <p>{{ quack.content }}</p>
                        {% if  quack.imgSrc!='' %}
                            <img src="{{ quack.imgSrc }}" alt="{{ quack.imgSrc }}">
                        {% endif %}
                        {% if app.user %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('app_quack_display', {'id': quack.id}) }}">
                                    <button class="btn">Masquer le Quack</button>
                                </a>
                            {% endif %}
                            {% if quack.duckID == app.user.id %}
                                <div class="card-actions justify-end">

                                    <a href="{{ path('delete_quack', {'id':quack.id}) }}">
                                        <button class="btn">Supprimer</button>
                                    </a>

                                    <a href="{{ path('modify_quack', {'id':quack.id}) }}">
                                        <button class="btn">Modifier le quack</button>
                                    </a>
                                </div>
                            {% endif %}
                        {% endif %}
                        <ul>
                            <li>{{ quack.createdAt|date("d/m/Y") }}</li>

                        </ul>
                        <a href="{{ path('app_comment', {'id': quack.id}) }}">Commentaire</a>
                    </div>
                </div>


                <br>
            {% endif %}
        {% endfor %}
    </ul>
    <a href="{{ path('add_quackForm') }}" class="flex justify-center gap-3.5 mb-8">
        <button class="btn btn-primary">Quacker !</button>
    </a>
{% endblock %}

templates/quack/modifyQuack.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('style.css') }}">
{% endblock %}
{% block body %}

    {#    <div class="flex justify-center"> #}
    {#        <div class="w-3/5 bg-primary flex justify-center"> #}
    {#            <div> #}
    {#                {{ form(form) }} #}
    {#            </div> #}

    {#        </div> #}
    {#    </div> #}
    <div class="flex justify-center">


        {{ form_start(form, {'attr':{'class':'w-full flex flex-col items-center'}}) }}
        {{ form_errors(form) }}
        <h2 class="card-title flex justify-center">Modifier le  Quack !</h2>
        {{ form_widget(form.content, {'attr':{'class': ' w-3/5 textarea textarea-error'}}) }}

        {{ form_row(form.save, {'attr':{'class':' btn btn-primary bg-primary text-white'  }}) }}
        {{ form_end(form) }}


    </div>

{% endblock %}